CREATE TABLE capsule
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(100)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    unique_link     VARCHAR(255)                            NOT NULL,
    body            TEXT                                    NOT NULL,
    expiration_date date                                    NOT NULL,
    is_processed    BOOLEAN                                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_capsule PRIMARY KEY (id)
);

ALTER TABLE capsule
    ADD CONSTRAINT uc_capsule_unique_link UNIQUE (unique_link);